version: "3.0"

networks:
  ultron:

volumes:
  air_cache:

services:
  ultron-backend:
    image: cosmtrek/air
    container_name: ultron-backend
    working_dir: /ultron-api
    networks:
      - ultron
    ports:
      - 3300:3300
    volumes:
      - ./:/ultron-api/
      - air_cache:/.cache
    environment:
      UID: ${USER}
      GID: ${USER}
      