## Define Host for the API server
host = ""
## Define Port for the API server
port = 3300

## Location for Turtle lua files
luafiles = "static"

## Ultron Data Directory
ultron_data = "../ultron_data"
